"""add sub_topics to user_preferences

Revision ID: 73565bc07d2f
Revises: 784d6d54e135
Create Date: 2026-03-30 14:05:47.358949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73565bc07d2f'
down_revision: Union[str, None] = '784d6d54e135'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_preferences', sa.Column('sub_topics', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_preferences', 'sub_topics')
    # ### end Alembic commands ###
