"""add topic_weights to user_preferences

Revision ID: 784d6d54e135
Revises: da83e501f185
Create Date: 2026-03-28 12:15:50.784736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '784d6d54e135'
down_revision: Union[str, None] = 'da83e501f185'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_preferences', sa.Column('topic_weights', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_preferences', 'topic_weights')
    # ### end Alembic commands ###
