"""add duration_seconds to article_view

Revision ID: ae0b1f9fe651
Revises: 73565bc07d2f
Create Date: 2026-04-01 20:35:11.651001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae0b1f9fe651'
down_revision: Union[str, None] = '73565bc07d2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article_view', sa.Column('duration_seconds', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article_view', 'duration_seconds')
    # ### end Alembic commands ###
