"""add title to chat_sessions

Revision ID: da83e501f185
Revises: 2e8197cd4d1b
Create Date: 2026-03-27 09:56:45.477757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da83e501f185'
down_revision: Union[str, None] = '2e8197cd4d1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'title')
    # ### end Alembic commands ###
